-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 08, 2025 at 07:57 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `shoppingcart`
--

-- --------------------------------------------------------

--
-- Table structure for table `buyers`
--

CREATE TABLE `buyers` (
  `id2` int(10) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `phone_number` varchar(20) NOT NULL,
  `email` varchar(255) NOT NULL,
  `order_date` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `buyers`
--

INSERT INTO `buyers` (`id2`, `name`, `phone_number`, `email`, `order_date`) VALUES
(1, 'Ana-Ioana Popescu', '0733298513', 'anapopescu2004@yahoo.com', '2025-01-19 19:07:47'),
(2, 'Ana-Ioana Popescu', '0733298513', 'anapopescu2004@yahoo.com', '2025-01-19 19:10:30'),
(3, 'Maria', '0756789056', 'maria@gmail.com', '2025-01-19 19:10:56'),
(4, 'Marian', '0789786756', 'marian@gmail.com', '2025-01-19 19:13:24'),
(5, 'Ioana', '0864675357', 'ioana@gmail.com', '2025-01-19 19:32:36'),
(6, 'Emil', '0789564534', 'emil@gmail.com', '2025-01-19 20:39:33'),
(7, 'Papuc Mihalache', '0734352678', 'mihai@yahoo.com', '2025-03-18 13:39:39');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `title` varchar(200) NOT NULL,
  `description` text NOT NULL,
  `price` decimal(7,2) NOT NULL,
  `rrp` decimal(7,2) NOT NULL DEFAULT 0.00,
  `quantity` int(11) NOT NULL,
  `img` text NOT NULL,
  `date_added` datetime NOT NULL DEFAULT current_timestamp(),
  `is_vegan` tinyint(4) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `title`, `description`, `price`, `rrp`, `quantity`, `img`, `date_added`, `is_vegan`) VALUES
(1, 'Chocolat au lait et \r\namandes &#128149;', '<p>Chocolat unique fait avec amour.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n<li>Chocolat au lait riche mélangé aux meilleures amandes grillées.</li>\r\n<li>Fabriqué à partir de fèves de cacao issues de sources durables.</li>\r\n<li>Parfaitement portionné pour partager ou se faire plaisir.</li>\r\n<li>Texture soyeuse avec un croquant satisfaisant à chaque bouchée.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Chaque tablette pèse 150 grammes et est réalisée avec 100 % d’ingrédients naturels, garantissant une qualité et une saveur irréprochables. Emballage éco-responsable pour préserver la fraîcheur et réduire l’impact environnemental.</p>', 30.00, 0.00, 21, 'ciocolata_lapte si migdale.jpg', '2024-12-26 13:47:26', 0),
(2, 'Chocolate avec des fraises&#128149;', '<p>Une expérience chocolatée incomparable.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n<li>Alliance parfaite entre un chocolat au lait fondant et des éclats de fraises délicatement séchées.</li>\r\n<li>Ingrédients soigneusement sélectionnés pour une qualité supérieure.</li>\r\n<li>Un mélange harmonieux de douceur et de notes fruitées.</li>\r\n<li>Fabriqué artisanalement pour garantir un goût authentique et raffiné.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Chaque tablette de 140 grammes est réalisée avec des fraises cueillies à la main et transformées pour préserver leur fraîcheur. Présenté dans un emballage raffiné, respectueux de l’environnement, parfait pour un moment de plaisir ou un cadeau spécial.</p>', 14.99, 19.99, 34, 'chocolate_packaging_strawberry.jpg', '2019-03-13 16:29:41', 0),
(3, 'Chocolat blanc avec du pistache&#128149;', '<p>Un chocolat d\'exception pour les vrais amateurs de pistaches.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n<li>Chocolat au lait velouté enrichi de véritables éclats de pistaches croquantes.</li>\r\n<li>Ingrédients haut de gamme pour une saveur intense et authentique.</li>\r\n<li>Un équilibre parfait entre douceur et caractère.</li>\r\n<li>Fabriqué selon un savoir-faire artisanal pour une expérience unique.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Cette tablette de 130 grammes marie la richesse du chocolat au lait à la subtilité des pistaches soigneusement torréfiées. Emballée dans un design élégant et recyclable, elle est idéale pour un moment gourmand ou pour offrir en toute occasion.</p>', 19.99, 0.00, 23, 'chocolate_packaging_pistachio.jpg', '2019-03-13 16:49:48', 0),
(4, 'Chocolat avec des oranges&#128149;', '<p>Une harmonie parfaite entre chocolat et agrumes.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n<li>Chocolat noir intense associé à des morceaux d’orange confite pour une explosion de saveurs.</li>\r\n<li>Ingrédients naturels sélectionnés pour leur qualité et leur fraîcheur.</li>\r\n<li>Un équilibre subtil entre la richesse du cacao et la vivacité des agrumes.</li>\r\n<li>Fabriqué artisanalement pour une texture et un goût incomparables.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Cette tablette de 150 grammes est confectionnée avec des oranges confites à la main pour une expérience gustative authentique. Présentée dans un emballage élégant et respectueux de l’environnement, elle est parfaite pour les amateurs de douceurs sophistiquées.</p>', 34.99, 0.00, 18, 'chocolate_packaging_orange_zest.jpg', '2019-03-13 16:34:04', 0),
(6, 'Chocolat noir avec du coffee&#128149;', '<p>Une expérience chocolatée raffinée pour les amateurs de café.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n<li>Alliance parfaite entre un chocolat noir intense et des notes riches de café.</li>\r\n<li>Ingrédients premium soigneusement sélectionnés pour une qualité supérieure.</li>\r\n<li>Une fusion harmonieuse de l\'amertume du cacao et de l\'arôme envoûtant du café.</li>\r\n<li>Fabriqué artisanalement pour garantir un goût authentique et sophistiqué.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Chaque tablette de 120 grammes est réalisée avec des fèves de cacao et du café fraîchement moulu, offrant une saveur profonde et équilibrée. Présenté dans un emballage élégant et écoresponsable, parfait pour une pause gourmande ou comme cadeau raffiné.</p>', 35.00, 0.00, 9, 'chocolate_packaging_coffee.jpg', '2024-12-26 14:25:40', 0),
(7, 'Chocolat à la menthe&#128149;', '<p>Un chocolat rafraîchissant et audacieux.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n<li>Chocolat noir intense infusé d’un arôme naturel de menthe fraîche.</li>\r\n<li>Une combinaison parfaite de douceur et de fraîcheur.</li>\r\n<li>Ingrédients de qualité supérieure, issus de sources responsables.</li>\r\n<li>Une texture fondante qui libère une explosion de saveurs à chaque bouchée.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Cette tablette de 120 grammes est élaborée avec du cacao pur et des extraits naturels de menthe. Présentée dans un emballage raffiné, recyclable et respectueux de l’environnement, elle est idéale pour un moment de détente ou comme cadeau raffiné.</p>', 14.79, 0.00, 15, 'chocolate_packaging_mint.jpg', '2024-12-27 16:36:35', 0),
(9, 'Chocolat aux noisettes&#128149;', '<p>Un délice croquant et irrésistible.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n<li>Chocolat au lait crémeux parsemé de généreux éclats de noisettes torréfiées.</li>\r\n<li>Ingrédients soigneusement sélectionnés pour une saveur authentique et gourmande.</li>\r\n<li>Un équilibre parfait entre douceur et croquant.</li>\r\n<li>Fabriqué avec un savoir-faire artisanal pour une expérience unique.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Cette tablette de 140 grammes marie le meilleur du cacao et des noisettes rigoureusement sélectionnées et torréfiées pour un goût riche et naturel. Présentée dans un emballage élégant et recyclable, parfaite pour les moments de plaisir ou pour offrir à vos proches.</p>', 18.99, 0.00, 12, 'chocolate_packaging_hazelnut.jpg', '2024-12-27 16:36:55', 0),
(10, 'Chocolat à la noix de coco&#128149;', '<p>Un voyage exotique dans chaque bouchée.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n<li>Chocolat au lait onctueux enrichi de délicats éclats de noix de coco.</li>\r\n<li>Ingrédients naturels pour une saveur douce et authentique.</li>\r\n<li>Un mélange harmonieux de douceur tropicale et de texture fondante.</li>\r\n<li>Fabriqué avec soin pour une qualité et un goût exceptionnels.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Cette tablette de 130 grammes est composée de chocolat premium et de noix de coco râpée et légèrement grillée, pour un parfum irrésistible. Présentée dans un emballage recyclable élégant, elle est parfaite pour les amateurs de saveurs tropicales ou pour offrir en cadeau.</p>', 20.00, 0.00, 9, 'chocolate_packaging_coconut.jpg', '2024-12-27 16:41:07', 0),
(11, 'Chocolat avec du chili&#128149;', '<p>Une expérience chocolatée audacieuse et épicée.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n<li>Chocolat noir intense rehaussé d’une pointe de chili pour une touche piquante.</li>\r\n<li>Un équilibre unique entre la richesse du cacao et le piquant subtil du piment.</li>\r\n<li>Ingrédients de haute qualité pour une saveur authentique et raffinée.</li>\r\n<li>Une explosion de sensations qui éveillent les papilles.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Cette tablette de 120 grammes est élaborée avec du cacao pur et un mélange de chili soigneusement dosé pour une chaleur délicate et agréable. Emballée dans un design moderne et recyclable, elle est parfaite pour les amateurs de chocolat qui aiment sortir des sentiers battus.</p>', 24.99, 0.00, 10, 'chocolate_packaging_chili.jpg', '2024-12-27 16:41:24', 0),
(12, 'Chocolat avec des myrtilles&#128149;', '<p>Un mariage exquis entre douceur et fruits sauvages.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n<li>Chocolat au lait délicat enrichi de véritables morceaux de myrtilles séchées.</li>\r\n<li>Un mélange harmonieux de saveurs sucrées et acidulées.</li>\r\n<li>Fabriqué avec des ingrédients naturels de première qualité.</li>\r\n<li>Une texture fondante ponctuée de touches fruitées.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Cette tablette de 135 grammes combine le meilleur du chocolat au lait et des myrtilles sélectionnées pour leur goût intense. Présentée dans un emballage élégant et respectueux de l’environnement, elle est idéale pour les moments gourmands ou pour offrir un cadeau plein de délicatesse.</p>', 21.90, 19.90, 7, 'chocolate_packaging_blueberry.jpg', '2024-12-27 16:45:50', 0),
(13, 'Chocolat aux roses <br> et framboises&#128149;', '<p>Un chocolat raffiné aux notes florales et fruitées.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n<li>Chocolat blanc velouté infusé d’essence naturelle de rose.</li>\r\n<li>Parsemé de morceaux de framboises séchées pour une touche acidulée.</li>\r\n<li>Un mélange unique de douceur florale et de fraîcheur fruitée.</li>\r\n<li>Fabriqué artisanalement avec des ingrédients de qualité supérieure.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Cette tablette de 125 grammes offre une expérience sensorielle délicate et sophistiquée. Conçue dans un emballage raffiné et recyclable, elle est parfaite pour un cadeau romantique ou un moment de plaisir élégant.</p>', 29.99, 0.00, 14, 'chocolate_with_roses_and_rasberryes.jpg', '2024-12-27 16:46:00', 0),
(14, 'Pot de chocolat végétalien&#128149;', '<p>Un chocolat raffiné aux éclats croquants de cacao pur.</p>\r\n  <h3>Caractéristiques</h3>\r\n  <ul>\r\n    <li>Chocolat noir intense enrichi de morceaux de fèves de cacao.</li>\r\n    <li>Une texture croustillante pour une dégustation unique.</li>\r\n    <li>Idéal pour les amateurs de chocolat puissant et corsé.</li>\r\n    <li>Fabriqué avec des ingrédients issus de l’agriculture biologique.</li>\r\n  </ul>\r\n  <p><strong>Détails :</strong> Ce pot de 200 grammes est parfait pour accompagner vos desserts ou à savourer seul. Emballage durable et respectueux de l’environnement.</p>\r\n\r\n  <!-- Cacao Percentage Section -->\r\n  <div style=\"margin-top: 20px;\">\r\n    <strong>Pourcentage de cacao :</strong>\r\n    <div style=\"display: flex; flex-direction: column; align-items: flex-start;\">\r\n      <div style=\"width: 100%; height: 10px; background: #86592d; margin: 2px;\"></div>\r\n      <div style=\"width: 100%; height: 10px; background: #86592d; margin: 2px;\"></div>\r\n      <div style=\"width: 100%; height: 10px; background: #86592d; margin: 2px;\"></div>\r\n      <div style=\"width: 100%; height: 10px; background: #86592d; margin: 2px;\"></div>\r\n      <div style=\"width: 100%; height: 10px; background: #86592d; margin: 2px;\"></div>\r\n      <div style=\"width: 100%; height: 10px; background: #86592d; margin: 2px;\"></div>\r\n      <div style=\"width: 100%; height: 10px; background: #86592d; margin: 2px;\"></div>\r\n      <div style=\"width: 100%; height: 10px; background: #e0e0e0; margin: 2px;\"></div>\r\n      <div style=\"width: 100%; height: 10px; background: #e0e0e0; margin: 2px;\"></div>\r\n      <div style=\"width: 100%; height: 10px; background: #e0e0e0; margin: 2px;\"></div>\r\n</div>\r\n</div>', 17.00, 20.00, 15, 'Vegan_Chocolate_Jar_Design_2.jpg', '2024-12-28 15:28:23', 1),
(15, 'Pot avec du chocolat des noisettes&#128149;', '<p>Un chocolat raffiné aux notes onctueuses de noisette et de cacao.</p> <h3>Caractéristiques</h3> <ul> <li>Chocolat fondant infusé d’essence naturelle de noisette.</li> <li>Enrichi de morceaux de noisettes grillées pour une texture croquante.</li> <li>Un équilibre parfait entre intensité et douceur.</li> <li>Fabriqué artisanalement avec des ingrédients 100 % végétaliens.</li> </ul> <p><strong>Détails :</strong> Ce pot de 200 grammes offre une expérience gourmande idéale pour tartiner ou savourer à la cuillère. Présenté dans un bocal élégant et réutilisable.</p>', 12.99, 0.00, 16, 'Vegan_Chocolate_Jar_Design.jpg', '2024-12-27 23:27:38', 1),
(16, 'Pot de chocolat végétalien à la menthe&#128149;', '<p>Un chocolat rafraîchissant aux saveurs mentholées et veloutées.</p> <h3>Caractéristiques</h3> <ul> <li>Chocolat noir infusé d’huile essentielle de menthe poivrée.</li> <li>Parsemé de cristaux de menthe pour une fraîcheur intense.</li> <li>Une fusion parfaite entre l’amertume du chocolat et la vivacité de la menthe.</li> <li>Confectionné artisanalement avec des ingrédients d’origine éthique.</li> </ul> <p><strong>Détails :</strong> Ce pot de 200 grammes est idéal pour une pause gourmande rafraîchissante. Parfait pour offrir ou pour les amateurs de saveurs mentholées.</p>', 18.99, 0.00, 16, 'Vegan_Chocolate_Jar_Design_3.jpg', '2024-12-28 16:12:21', 1),
(17, 'Pot de chocolat végétalien avec caramel&#128149;', '<p>Un chocolat doux et gourmand aux nuances de caramel fondant.</p> <h3>Caractéristiques</h3> <ul> <li>Chocolat au lait végétalien avec un tourbillon de caramel.</li> <li>Rehaussé de cristaux de sel marin pour un contraste savoureux.</li> <li>Une harmonie parfaite entre douceur et caractère.</li> <li>Fabriqué sans aucun ingrédient d’origine animale.</li> </ul> <p><strong>Détails :</strong> Ce pot de 200 grammes est une véritable invitation à la gourmandise. Présenté dans un bocal raffiné et écologique.</p>', 16.99, 0.00, 15, 'Caramel_Swirl_Jar_Design.jpg', '2024-12-28 16:12:36', 1),
(18, 'Chocolat vegan avec du noix<br>de coco&#128149;', '<p>Un chocolat délicieusement exotique aux saveurs riches de noix de coco.</p> <h3>Caractéristiques</h3> <ul> <li>Chocolat blanc végétalien subtilement parfumé à l’essence naturelle de noix de coco.</li> <li>Enrichi de morceaux de noix de coco râpée pour une texture unique.</li> <li>Un équilibre parfait entre douceur crémeuse et fraîcheur tropicale.</li> <li>Fabriqué artisanalement avec des ingrédients biologiques et sans produits d’origine animale.</li> </ul> <p><strong>Détails :</strong> Ce pot de 200 grammes est idéal pour les amateurs de saveurs exotiques et gourmandes. Présenté dans un emballage raffiné et respectueux de l’environnement.</p>', 23.99, 0.00, 18, 'Chocolat_vegan_avec_noix_de_cocos.png', '2024-12-28 17:43:32', 1),
(19, 'Pot avec du miel et <br> du pistache&#128149;', '<p>Un chocolat raffiné aux saveurs uniques de miel et de pistache.</p> <h3>Caractéristiques</h3> <ul> <li>Chocolat doux enrichi d’essence naturelle de miel.</li> <li>Parsemé de pistaches grillées pour une texture croquante.</li> <li>Un mélange équilibré entre douceur florale et caractère noix.</li> <li>Fabriqué artisanalement avec des ingrédients issus de l’agriculture biologique.</li> </ul> <p><strong>Détails :</strong> Ce pot de 200 grammes offre une expérience unique et raffinée. Idéal pour accompagner vos desserts ou pour offrir en cadeau.</p>', 24.90, 0.00, 10, 'Honey_Pistachio_Jar_Design.jpg', '2024-12-28 18:55:20', 1),
(20, 'Pot avec du chocolat <br> de myrtille et de lavande', '<p>Un chocolat délicat et apaisant aux notes florales de lavande et de myrtilles.</p> <h3>Caractéristiques</h3> <ul> <li>Chocolat noir infusé d’essence naturelle de lavande.</li> <li>Parsemé de morceaux de myrtilles séchées pour une douceur fruitée.</li> <li>Une harmonie parfaite entre floralité et fraîcheur fruitée.</li> <li>Fabriqué artisanalement avec des ingrédients de haute qualité.</li> </ul> <p><strong>Détails :</strong> Ce pot de 200 grammes est idéal pour un moment de détente et de gourmandise. Conçu dans un emballage élégant et respectueux de l’environnement.</p>', 31.90, 29.90, 10, 'Lavender_Blueberry_Jar_Design.jpg', '2024-12-28 18:59:18', 1),
(21, 'Pot avec du chocolat <br> de matcha et de framboise&#128149;', '<p>Un chocolat vibrant aux notes exotiques de matcha et de framboises.</p> <h3>Caractéristiques</h3> <ul> <li>Chocolat blanc velouté infusé de thé matcha japonais.</li> <li>Rehaussé de morceaux de framboises acidulées.</li> <li>Une fusion parfaite entre amertume subtile et fraîcheur fruitée.</li> <li>Fabriqué artisanalement avec des ingrédients de qualité supérieure.</li> </ul> <p><strong>Détails :</strong> Ce pot de 200 grammes est idéal pour une dégustation originale et surprenante. Emballage recyclable et élégant.</p>', 31.90, 29.90, 2, 'Matcha_Raspberry_Jar_Design.jpg', '2024-12-28 18:59:28', 1),
(23, 'Pot avec du chocolat <br> de cocos et de lime&#128149;', '<p>Un chocolat tropical et rafraîchissant aux saveurs de noix de coco, citron vert et sel de mer.</p> <h3>Caractéristiques</h3> <ul> <li>Chocolat blanc végétalien infusé d’essence de noix de coco.</li> <li>Rehaussé de zestes de citron vert pour une fraîcheur vive.</li> <li>Une pointe de sel de mer pour sublimer les saveurs tropicales.</li> <li>Fabriqué artisanalement avec des ingrédients d’origine naturelle.</li> </ul> <p><strong>Détails :</strong> Ce pot de 200 grammes évoque une évasion tropicale avec chaque bouchée. Emballage durable et élégant.</p>', 28.90, 0.00, 19, 'Salted_Coconut_Lime_Jar_Design.jpg', '2024-12-28 19:03:47', 1),
(24, 'Pot avec du chocolat <br> de rose et de cardamome&#128149;', '<p>Un chocolat sophistiqué aux saveurs exotiques de rose et de cardamome.</p> <h3>Caractéristiques</h3> <ul> <li>Chocolat au lait végétalien délicatement parfumé à l’essence de rose.</li> <li>Rehaussé d’une touche subtile de cardamome pour une profondeur aromatique.</li> <li>Une expérience luxueuse et florale pour les amateurs de saveurs uniques.</li> <li>Fabriqué artisanalement avec des ingrédients biologiques et éthiques.</li> </ul> <p><strong>Détails :</strong> Ce pot de 200 grammes est parfait pour un cadeau raffiné ou un moment de plaisir élégant.</p>', 29.99, 0.00, 20, 'Rose_Cardamom_Jar_Design.jpg', '2024-12-28 19:04:06', 1),
(27, 'Pot avec du chocolat <br> de mango et chili&#128149;', '<p>Un chocolat audacieux aux saveurs tropicales et épicées de mangue et de piment.</p> <h3>Caractéristiques</h3> <ul> <li>Chocolat au lait végétalien infusé d’arômes naturels de mangue.</li> <li>Un soupçon de piment pour une touche épicée inattendue.</li> <li>Une combinaison parfaite entre douceur et chaleur.</li> <li>Fabriqué artisanalement avec des ingrédients éthiques et durables.</li> </ul> <p><strong>Détails :</strong> Ce pot de 200 grammes offre une explosion de saveurs tropicales et épicées. Parfait pour les amateurs de nouvelles expériences gustatives.</p>', 24.99, 0.00, 1, 'Spicy_Mango_Jar_Design.jpg', '2024-12-28 19:07:47', 1),
(29, 'Chocolat avec du <br> fruit de la passion&#128149;', '<div style=\"text-align: center; font-family: Arial, sans-serif; margin: 20px;\">\r\n    <h2 style=\"color: #FFA500;\">White Chocolate with Passionfruit</h2>\r\n    <p style=\"font-size: 16px; line-height: 1.6;\">\r\n        Indulge in the exotic sweetness of creamy white chocolate paired with the vibrant, tangy notes of fresh passionfruit. \r\n        The elegant packaging showcases swirling chocolate designs intertwined with golden-yellow passionfruit highlights, \r\n        evoking a tropical escape. Perfect for those seeking a luxurious and unique chocolate experience.\r\n    </p>\r\n</div>\r\n<div>\r\n<p>Une expérience chocolatée raffinée pour les amateurs d\'exotisme.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n    <li>Alliance parfaite entre un chocolat blanc crémeux et la fraîcheur acidulée du fruit de la passion.</li>\r\n    <li>Ingrédients premium soigneusement sélectionnés pour une qualité supérieure.</li>\r\n    <li>Un équilibre harmonieux entre la douceur du chocolat blanc et les notes tropicales du fruit.</li>\r\n    <li>Fabriqué artisanalement pour garantir un goût authentique et sophistiqué.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Chaque tablette de 120 grammes est réalisée avec du chocolat blanc de qualité supérieure et des fruits de la passion frais, offrant une saveur lumineuse et équilibrée. Présenté dans un emballage élégant et écoresponsable, parfait pour une pause gourmande ou comme cadeau raffiné.</p>', 35.99, 0.00, 18, 'Chocolate_with_passion_fruit.jpg', '2024-12-29 17:53:12', 0),
(30, 'Chocolat avec des <br> oranges rouges&#128149;', '<p>Une expérience chocolatée intense pour les amateurs de saveurs fruitées et corsées.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n    <li>Alliance parfaite entre un chocolat noir riche et la vivacité des oranges sanguines.</li>\r\n    <li>Ingrédients premium soigneusement sélectionnés pour une qualité supérieure.</li>\r\n    <li>Un mariage exquis entre l\'amertume du cacao et les notes acidulées d\'agrumes.</li>\r\n    <li>Fabriqué artisanalement pour garantir un goût authentique et sophistiqué.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Chaque tablette de 120 grammes est composée de chocolat noir intense et de véritables tranches d\'oranges sanguines, offrant une saveur profonde et vibrante. Présenté dans un emballage élégant et écoresponsable, idéal pour les amateurs de chocolat haut de gamme.</p>', 32.99, 0.00, 31, 'Chocolat_Blood_Orange.jpg', '2024-12-29 18:15:14', 0),
(31, 'Chocolat avec ananas&#128149;', '<p>Une expérience chocolatée tropicale pour les amateurs de saveurs exotiques.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n    <li>Alliance parfaite entre un chocolat blanc onctueux et la douceur acidulée de l\'ananas.</li>\r\n    <li>Ingrédients premium soigneusement sélectionnés pour une qualité supérieure.</li>\r\n    <li>Une fusion harmonieuse de la douceur du chocolat blanc et des notes fruitées tropicales.</li>\r\n    <li>Fabriqué artisanalement pour garantir un goût authentique et sophistiqué.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Chaque tablette de 120 grammes est réalisée avec du chocolat blanc de qualité supérieure et des morceaux d\'ananas juteux, offrant une saveur lumineuse et équilibrée. Présenté dans un emballage élégant et écoresponsable, parfait pour une pause gourmande ou comme cadeau raffiné.</p>', 35.90, 0.00, 35, 'Chocolat_avec_pineapple.jpg', '2024-12-29 18:19:52', 0),
(32, 'Chocolat avec du kiwi&#128149;', '<p>Une expérience chocolatée unique pour les amateurs de saveurs rafraîchissantes.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n    <li>Alliance parfaite entre un chocolat au lait doux et la vivacité des kiwis.</li>\r\n    <li>Ingrédients premium soigneusement sélectionnés pour une qualité supérieure.</li>\r\n    <li>Un mélange équilibré entre la douceur crémeuse du chocolat au lait et la fraîcheur acidulée du kiwi.</li>\r\n    <li>Fabriqué artisanalement pour garantir un goût authentique et sophistiqué.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Chaque tablette de 120 grammes combine chocolat au lait de qualité supérieure et kiwis frais pour une expérience unique. Présenté dans un emballage élégant et écoresponsable, parfait pour offrir ou s’offrir une gourmandise fruitée.</p>', 31.99, 0.00, 20, 'Chocolat_avec_kiwi.jpg', '2024-12-29 18:23:45', 0),
(33, 'Chocolat avec du <br> lychee&#128149;', '<p>Une expérience chocolatée délicate pour les amateurs de saveurs florales.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n    <li>Alliance parfaite entre un chocolat rubis rare et le parfum délicat du litchi.</li>\r\n    <li>Ingrédients premium soigneusement sélectionnés pour une qualité supérieure.</li>\r\n    <li>Un mariage harmonieux entre l\'acidité subtile du chocolat rubis et les arômes exotiques du litchi.</li>\r\n    <li>Fabriqué artisanalement pour garantir un goût authentique et sophistiqué.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Chaque tablette de 120 grammes est composée de chocolat rubis raffiné et de litchis frais, offrant une saveur florale et gourmande. Présenté dans un emballage élégant et écoresponsable, idéal pour un cadeau ou une dégustation raffinée.</p>', 40.00, 0.00, 26, 'Chocolat_avec_lycee.jpg', '2024-12-29 18:25:11', 0),
(34, 'Chocolat a noix de coco <br> et ananas&#128149;', '<p>Une expérience chocolatée tropicale pour les amateurs d\'évasion gustative.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n    <li>Alliance parfaite entre un chocolat blanc onctueux, la noix de coco et l\'ananas.</li>\r\n    <li>Ingrédients premium soigneusement sélectionnés pour une qualité supérieure.</li>\r\n    <li>Une fusion harmonieuse de la douceur du chocolat blanc et des saveurs tropicales fraîches.</li>\r\n    <li>Fabriqué artisanalement pour garantir un goût authentique et sophistiqué.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Chaque tablette de 120 grammes est réalisée avec du chocolat blanc de qualité et des morceaux de coco et d\'ananas, offrant une saveur tropicale et équilibrée. Présenté dans un emballage élégant et écoresponsable, idéal pour une pause gourmande ou un cadeau original.</p>', 39.99, 0.00, 25, 'Chocolate_with_cocos and ananas.jpg', '2024-12-29 18:28:16', 0),
(35, 'Chocolat avec le fruit <br> de dragon&#128149;', '<p>Une expérience chocolatée végane et tropicale, mettant en avant les saveurs exotiques.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n    <li>Alliance parfaite entre un chocolat noir intense et la douceur du fruit du dragon.</li>\r\n    <li>Ingrédients 100% véganes et soigneusement sélectionnés pour une qualité exceptionnelle.</li>\r\n    <li>Un équilibre subtil entre l\'amertume du cacao et les arômes tropicaux légers.</li>\r\n    <li>Présence visuelle claire de l\'identité végane sur l\'emballage.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Chaque tablette de 120 grammes est réalisée avec du chocolat noir végan et des fruits du dragon frais, offrant une expérience visuellement et gustativement remarquable. Parfait pour une pause gourmande ou un cadeau sophistiqué.</p>', 36.90, 0.00, 19, 'Chocolate_with_dragon_fruit.jpg', '2024-12-29 18:34:01', 1),
(37, 'Chocolat avec mango <br> et turmeric&#128149;', '<p>Une expérience chocolatée végane pour les amateurs de saveurs audacieuses et épicées.</p>\r\n<h3>Caractéristiques</h3>\r\n<ul>\r\n    <li>Alliance parfaite entre un chocolat noir intense, la douceur du mangue et la chaleur subtile du curcuma.</li>\r\n    <li>Ingrédients 100% véganes, biologiques et de haute qualité.</li>\r\n    <li>Une fusion harmonieuse de l\'amertume du cacao et des arômes épicés et fruités.</li>\r\n    <li>Fabriqué artisanalement pour garantir un goût authentique et unique.</li>\r\n</ul>\r\n<p><strong>Détails :</strong> Chaque tablette de 120 grammes combine chocolat noir végan, mangue juteuse et curcuma aromatique pour une saveur profonde et équilibrée. Présenté dans un emballage élégant et écoresponsable, parfait pour les amateurs de découvertes gustatives.</p>', 33.99, 0.00, 27, 'Chocolate_with_mango_and_turmeric.jpg', '2024-12-29 18:36:05', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `buyers`
--
ALTER TABLE `buyers`
  ADD PRIMARY KEY (`id2`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `buyers`
--
ALTER TABLE `buyers`
  MODIFY `id2` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
